FORM_KEY_VERIFICATION = "verification"
VERIFICATION_FORM_PATH = "data/forms/verification.json"

VALID_FORM_KEY_PATTERN_TEXT = r"^[a-z0-9_]{1,40}$"
VALID_QUESTION_KEY_PATTERN_TEXT = r"^[a-z0-9_]{1,80}$"

GENERIC_FORM_BUTTON_CUSTOM_ID = "form:start"